spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: profile-service